In [17]:
# let's say i'm going to record the climate temperature in different times a day for 3 days by using Numpy 

import numpy as np
My_list=[[80,67,55,90],
        [60,88,70,98],
        [52,77,87,78]]

climate_array=np.array(My_list)
print(climate_array)

# days are columns(monday,tuesday,wednesday), rows are the changes in the temperature a day


[[80 67 55 90]
 [60 88 70 98]
 [52 77 87 78]]


In [18]:
# let's use some operation in our array
# what if the temperature was not accurate ! it's less than the accurate by 4 points ! it is easy to solve this :
climate_fixed=climate_array+4
print(climate_fixed)

[[ 84  71  59  94]
 [ 64  92  74 102]
 [ 56  81  91  82]]


In [22]:
# i want to select all the temperature of the first day which is monday 
monday_temperatures=climate_fixed[0,:]
print(monday_temperatures)

[84 71 59 94]


In [20]:
# now i want to select a same record time of temperature in diffrenet days
climate_fixed[:,2]

array([59, 74, 91])

In [24]:
# let's select the all the temperature between 70 and 90
temperature=climate_fixed[(climate_fixed >= 70) & (climate_fixed <= 90)]
print(temperature)

[84 71 74 81 82]
